<?php


class Potoky_Surprise_Model_Resource_Surprise_Collection extends Mage_Core_Model_Resource_Db_Collection_Abstract
{
    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('potoky_surprise/surprise');
    }
}